name: CI

on: push

env:
    CARGO_TERM_COLOR: always

jobs:
    ci:
        runs-on: ubuntu-latest
        name: CI
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Cache
              uses: actions/cache@v3
              continue-on-error: false
              with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: ${{ runner.os }}-cargo-
            - name: Test
              run: cargo test
            - name: Lint
              run: cargo clippy -- -D warnings
            - name: Format
              run: cargo fmt --check
            - name: Benchmark
              run: cargo time --all --store
            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: "ci: update benchmarks"
